### ISSUE TITLE
UWP build problems with Visual Studio 2017 (platform tools v141)

### ISSUE THREAD

**Issue by mstorch** [Microsoft/xbox-live-samples#35] opened 2017-05-09 20:26 UTC
The xbox-live-samples build and run fine when using Visual Studio 2015 (platform tools v140) but fail during the linker step when building with Visual Studio 2017 (platform tools v141).

I have not tried all solutions, but for example, using VS 2017, if you open Samples\ID@XboxSDK\Achievements\UWP\Cpp\Achievements.sln, re-target for platform tools v141, and then build for Local or Remote debugging, you will encounter the following errors (sorry, it's a bit long):

`1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: __cdecl xbox::services::leaderboard::leaderboard_query::leaderboard_query(void)" (??0leaderboard_query@leaderboard@services@xbox@@QEAA@XZ) referenced in function "public: __cdecl xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_query>::xbox_live_result<class xbox::services::leaderboard::leaderboard_query>(class std::error_code,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (??0?$xbox_live_result@Vleaderboard_query@leaderboard@services@xbox@@@services@xbox@@QEAA@Verror_code@std@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: bool __cdecl xbox::services::leaderboard::leaderboard_query::skip_result_to_me(void)const " (?skip_result_to_me@leaderboard_query@leaderboard@services@xbox@@QEBA_NXZ) referenced in function "public: class xbox::services::xbox_live_result<void> __cdecl xbox::services::stats::manager::stats_manager_impl::get_leaderboard(class std::shared_ptr<class xbox::services::system::xbox_live_user> const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard@stats_manager_impl@manager@stats@services@xbox@@QEAA?AV?$xbox_live_result@X@45@AEBV?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@8@Vleaderboard_query@leaderboard@45@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: unsigned int __cdecl xbox::services::leaderboard::leaderboard_query::skip_result_to_rank(void)const " (?skip_result_to_rank@leaderboard_query@leaderboard@services@xbox@@QEBAIXZ) referenced in function "public: class xbox::services::xbox_live_result<void> __cdecl xbox::services::stats::manager::stats_manager_impl::get_leaderboard(class std::shared_ptr<class xbox::services::system::xbox_live_user> const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard@stats_manager_impl@manager@stats@services@xbox@@QEAA?AV?$xbox_live_result@X@45@AEBV?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@8@Vleaderboard_query@leaderboard@45@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: unsigned int __cdecl xbox::services::leaderboard::leaderboard_query::max_items(void)const " (?max_items@leaderboard_query@leaderboard@services@xbox@@QEBAIXZ) referenced in function "public: class xbox::services::xbox_live_result<void> __cdecl xbox::services::stats::manager::stats_manager_impl::get_leaderboard(class std::shared_ptr<class xbox::services::system::xbox_live_user> const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard@stats_manager_impl@manager@stats@services@xbox@@QEAA?AV?$xbox_live_result@X@45@AEBV?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@8@Vleaderboard_query@leaderboard@45@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: enum xbox::services::leaderboard::sort_order __cdecl xbox::services::leaderboard::leaderboard_query::order(void)const " (?order@leaderboard_query@leaderboard@services@xbox@@QEBA?AW4sort_order@234@XZ) referenced in function "public: class xbox::services::xbox_live_result<void> __cdecl xbox::services::stats::manager::stats_manager_impl::get_social_leaderboard(class std::shared_ptr<class xbox::services::system::xbox_live_user> const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_social_leaderboard@stats_manager_impl@manager@stats@services@xbox@@QEAA?AV?$xbox_live_result@X@45@AEBV?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@8@1Vleaderboard_query@leaderboard@45@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const & __cdecl xbox::services::leaderboard::leaderboard_query::_Continuation_token(void)const " (?_Continuation_token@leaderboard_query@leaderboard@services@xbox@@QEBAAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@XZ) referenced in function "public: class xbox::services::xbox_live_result<void> __cdecl xbox::services::stats::manager::stats_manager_impl::get_leaderboard(class std::shared_ptr<class xbox::services::system::xbox_live_user> const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard@stats_manager_impl@manager@stats@services@xbox@@QEAA?AV?$xbox_live_result@X@45@AEBV?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@8@Vleaderboard_query@leaderboard@45@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: void __cdecl xbox::services::leaderboard::leaderboard_query::_Set_continuation_token(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (?_Set_continuation_token@leaderboard_query@leaderboard@services@xbox@@QEAAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z) referenced in function "class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> __cdecl xbox::services::leaderboard::serializers::deserialize_result(class web::json::value const &,class std::shared_ptr<class xbox::services::user_context>,class std::shared_ptr<class xbox::services::xbox_live_context_settings>,class std::shared_ptr<class xbox::services::xbox_live_app_config>,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?deserialize_result@serializers@leaderboard@services@xbox@@YA?AV?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@34@AEBVvalue@json@web@@V?$shared_ptr@Vuser_context@services@xbox@@@std@@V?$shared_ptr@Vxbox_live_context_settings@services@xbox@@@std@@V?$shared_ptr@Vxbox_live_app_config@services@xbox@@@std@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@Vleaderboard_query@234@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: void __cdecl xbox::services::leaderboard::leaderboard_query::_Set_stat_name(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (?_Set_stat_name@leaderboard_query@leaderboard@services@xbox@@QEAAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z) referenced in function "private: class Concurrency::task<class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> > __cdecl xbox::services::leaderboard::leaderboard_service::get_leaderboard_for_social_group_internal(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,unsigned int,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,unsigned int,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard_for_social_group_internal@leaderboard_service@leaderboard@services@xbox@@AEAA?AV?$task@V?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@services@xbox@@@Concurrency@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@000I00I00Vleaderboard_query@234@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: void __cdecl xbox::services::leaderboard::leaderboard_query::_Set_social_group(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (?_Set_social_group@leaderboard_query@leaderboard@services@xbox@@QEAAXAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z) referenced in function "private: class Concurrency::task<class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> > __cdecl xbox::services::leaderboard::leaderboard_service::get_leaderboard_for_social_group_internal(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,unsigned int,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,unsigned int,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class xbox::services::leaderboard::leaderboard_query)" (?get_leaderboard_for_social_group_internal@leaderboard_service@leaderboard@services@xbox@@AEAA?AV?$task@V?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@services@xbox@@@Concurrency@@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@000I00I00Vleaderboard_query@234@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: __cdecl xbox::services::stats::manager::leaderboard_result_event_args::leaderboard_result_event_args(class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> const &)" (??0leaderboard_result_event_args@manager@stats@services@xbox@@QEAA@AEBV?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@34@@Z) referenced in function "public: __cdecl std::_Ref_count_obj<class xbox::services::stats::manager::leaderboard_result_event_args>::_Ref_count_obj<class xbox::services::stats::manager::leaderboard_result_event_args><class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> const &>(class xbox::services::xbox_live_result<class xbox::services::leaderboard::leaderboard_result> const &)" (??$?0AEBV?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@services@xbox@@@?$_Ref_count_obj@Vleaderboard_result_event_args@manager@stats@services@xbox@@@std@@QEAA@AEBV?$xbox_live_result@Vleaderboard_result@leaderboard@services@xbox@@@services@xbox@@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: __cdecl xbox::services::tournaments::tournament_service::tournament_service(void)" (??0tournament_service@tournaments@services@xbox@@QEAA@XZ) referenced in function "public: __cdecl xbox::services::xbox_live_context_impl::xbox_live_context_impl(class std::shared_ptr<class xbox::services::system::xbox_live_user>)" (??0xbox_live_context_impl@services@xbox@@QEAA@V?$shared_ptr@Vxbox_live_user@system@services@xbox@@@std@@@Z)
1>Microsoft.Xbox.Services.141.UWP.Ship.Cpp.lib(build.obj) : error LNK2019: unresolved external symbol "public: __cdecl xbox::services::tournaments::tournament_service::tournament_service(class std::shared_ptr<class xbox::services::user_context>,class std::shared_ptr<class xbox::services::xbox_live_context_settings>,class std::shared_ptr<class xbox::services::xbox_live_app_config>,class std::shared_ptr<class xbox::services::real_time_activity::real_time_activity_service>)" (??0tournament_service@tournaments@services@xbox@@QEAA@V?$shared_ptr@Vuser_context@services@xbox@@@std@@V?$shared_ptr@Vxbox_live_context_settings@services@xbox@@@5@V?$shared_ptr@Vxbox_live_app_config@services@xbox@@@5@V?$shared_ptr@Vreal_time_activity_service@real_time_activity@services@xbox@@@5@@Z) referenced in function "public: void __cdecl xbox::services::xbox_live_context_impl::init(void)" (?init@xbox_live_context_impl@services@xbox@@QEAAXXZ)`

**Comment by jasonsandlin** [comment] 2017-05-09 21:30
Thanks for the bug report.  I can confirm this is a bug.  We'll fix this soon

**Comment by jasonsandlin** [comment] 2017-05-15 19:10
This is fixed now.  I've also added VS2017 support to all the samples, so just open any of the *_2017.sln projects.

**Closed** 2017-05-18 08:19 UTC

**Comment by ShaheedLegion** [comment] 2020-12-15 07:42
Sorry to bug you, how did you fix this issue? I'm having the same problem with a personal project that I started in vs2017, but am now continuing in vs2019 - it won't compile due to the same errors.

**Comment by ShaheedLegion** [comment] 2020-12-17 13:36
> Sorry to bug you, how did you fix this issue? I'm having the same problem with a personal project that I started in vs2017, but am now continuing in vs2019 - it won't compile due to the same errors.

Hi, so - just so you know, I never found a way to solve this - the only way forward was for me to reinstall VS2017 and continue developing the project using that IDE.
